#!/usr/bin/env python3
"""
Generate Python bindings for ExprType enum from expression.h

This script extracts all ExprType enum values from expression.h and generates
the nanobind binding code, similar to how dialect mappings are auto-generated.

Usage:
    python3 scripts/generate_expr_type_bindings.py > src/python/expr_type_bindings_generated.h
"""

import re
import sys
from pathlib import Path

def extract_expr_types(expression_h_path):
    """Extract all ExprType enum values from expression.h"""
    with open(expression_h_path, 'r') as f:
        lines = f.readlines()

    in_enum = False
    enum_values = []

    for line in lines:
        if 'enum class ExprType' in line:
            in_enum = True
            continue
        if in_enum:
            if line.strip() == '};':
                break
            # Remove comments
            line = re.sub(r'//.*$', '', line)
            # Find all uppercase identifiers followed by comma or semicolon
            matches = re.findall(r'\b([A-Z_][A-Z_0-9]*)\b(?=\s*[,;])', line)
            enum_values.extend(matches)

    # Remove duplicates while preserving order
    seen = set()
    unique_values = []
    for val in enum_values:
        if val not in seen:
            seen.add(val)
            unique_values.append(val)

    return unique_values

def generate_bindings(enum_values):
    """Generate the nanobind binding code"""
    print(f"// Auto-generated by scripts/generate_expr_type_bindings.py")
    print(f"// DO NOT EDIT MANUALLY - regenerate using:")
    print(f"//   python3 scripts/generate_expr_type_bindings.py > src/python/expr_type_bindings_generated.h")
    print(f"// Source: include/libsqlglot/expression.h")
    print(f"// Total values: {len(enum_values)}")
    print()
    print("// ExprType enum – ALL values auto-generated from expression.h")
    print('nb::enum_<ExprType>(m, "ExprType")')
    for val in enum_values:
        print(f'    .value("{val}", ExprType::{val})')
    print('    .export_values();')

def main():
    # Get project root
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    expression_h = project_root / "include" / "libsqlglot" / "expression.h"

    if not expression_h.exists():
        print(f"Error: {expression_h} not found", file=sys.stderr)
        sys.exit(1)

    enum_values = extract_expr_types(expression_h)
    generate_bindings(enum_values)

if __name__ == "__main__":
    main()
