#!/usr/bin/env python3
"""
Generate dialect reflection mappings from the Dialect enum.

This script parses include/libsqlglot/dialects.h and generates
include/libsqlglot/dialect_reflection_generated.h with a constexpr
array mapping dialect names to enum values.

This is a PROPER solution to the GCC 16 reflection bug where
enumerators_of() cannot be used in constexpr contexts.
"""

import re
import sys
from pathlib import Path


def parse_dialect_enum(header_path: Path) -> list[str]:
    """Parse the Dialect enum from dialects.h and extract all dialect names."""
    content = header_path.read_text()

    # Find the Dialect enum definition
    enum_match = re.search(
        r'enum\s+class\s+Dialect\s*\{(.*?)\};',
        content,
        re.DOTALL
    )

    if not enum_match:
        raise ValueError("Could not find 'enum class Dialect' in dialects.h")

    enum_body = enum_match.group(1)

    # Extract all identifiers (dialect names)
    dialects = []
    for line in enum_body.split('\n'):
        # Remove comments
        line = re.sub(r'//.*$', '', line)
        line = line.strip()

        # Skip empty lines and comments
        if not line or line.startswith('//'):
            continue

        # Extract identifier (before comma or end)
        match = re.match(r'([A-Za-z0-9_]+)', line)
        if match:
            dialect = match.group(1)
            # Skip the COUNT sentinel
            if dialect != 'COUNT':
                dialects.append(dialect)

    return dialects


def generate_header(dialects: list[str]) -> str:
    """Generate the reflection header file content."""

    # Generate the array initializer
    mappings = ',\n        '.join(
        f'{{"{dialect}", Dialect::{dialect}}}'
        for dialect in dialects
    )

    header = f'''#pragma once

// THIS FILE IS AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/generate_dialect_reflection.py from include/libsqlglot/dialects.h

#include <libsqlglot/dialects.h>

namespace libsqlglot::dialects {{

/// Dialect name-value mapping
struct DialectMapping {{
    const char* name;
    Dialect value;

    constexpr DialectMapping() noexcept : name(""), value(Dialect::ANSI) {{}}
    constexpr DialectMapping(const char* n, Dialect v) noexcept
        : name(n), value(v) {{}}
}};

namespace detail {{
    // Auto-generated dialect mappings from the Dialect enum
    inline constexpr DialectMapping dialect_mappings_storage[] = {{
        {mappings}
    }};
}}

// Access the mappings
inline constexpr const DialectMapping* dialect_mappings = detail::dialect_mappings_storage;
inline constexpr size_t DIALECT_COUNT = sizeof(detail::dialect_mappings_storage) / sizeof(DialectMapping);

// Compile-time verification
static_assert(DIALECT_COUNT > 0, "No dialects found");
static_assert(DIALECT_COUNT == static_cast<size_t>(Dialect::COUNT),
              "Generated dialect count must match enum COUNT");

}} // namespace libsqlglot::dialects
'''

    return header


def main():
    if len(sys.argv) != 3:
        print("Usage: generate_dialect_reflection.py <dialects.h> <output.h>")
        sys.exit(1)

    input_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])

    # Parse the enum
    dialects = parse_dialect_enum(input_path)

    print(f"Found {len(dialects)} dialects in {input_path}")

    # Generate the header
    header_content = generate_header(dialects)

    # Write the output
    output_path.write_text(header_content)

    print(f"Generated {output_path}")


if __name__ == '__main__':
    main()
